pharse = "Ahmad Mosaku"
print("Ahmad\nMosaku")
print("Ahmad\"Mosaku")
print("Ahmad\Mosaku")
print(pharse + " is cool")
print(pharse.lower())
print(pharse.upper())
print(pharse.isupper())
print(pharse.upper().isupper())
print(len(pharse))
print(pharse[0])
print(pharse[1])
print(pharse[2])
print(pharse[-5])
print(pharse[3])
print(pharse.index("Mosaku"))
print(pharse.index("d"))
print(pharse.replace("Mosaku", "Oluwaseun"))
print(pharse.replace("Mosaku", "Oluwaseun" + " Hamid-Mosaku"))