Your_name = input("Enter your name:")
Your_age = input("Enter your age:")
crushers_name = input("Enter your crushers name:")
Your_School_name = input("Enter your Your School name:")
Your_Work_address = input("Enter your Your Work address:")
Your_property = input("Enter your Your property:")
print("I am " + Your_name)
print("I am " + Your_age)
print("I love " + crushers_name)
print("I study at " + Your_School_name)
print("I work at " + Your_Work_address)
print("I have " + Your_property)